name: JOSHUASMITH
favicon: null
layout_spectrum: 0.51187
typography_spectrum: 0.49415
title: Get to know me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4375
  lightness: 0.27119072154164314
  saturation: 0.5535993981175125
  rhythmicContrast: 0.2818873175419867
purpose: []
